
version: "3.9"
services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb:najat
    env_file:
      - .env
    restart: on-failure
    # volumes:
    #  - ./data:/var/lib/mysql
    networks:
      -  inception
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:najat
    ports:
      - 443:443
    restart: on-failure
    networks:
      -  inception
    # volumes:
    #   - wordpress:/var/www/html
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress:najat
    restart: on-failure
    volumes:
      - Wordpress:/var/www/html
    networks:
      -  inception
    env_file:
      - .env
    depends_on:
      - mariadb


volumes:
  Wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nkhoudro/Desktop/data/wp

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/nkhoudro/Desktop/data/db

networks:
  inception:
    name: inception