version : '3.8'
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    restart: always
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydata
      MYSQL_USER: najat
      MYSQL_PASSWORD: password
    restart: always
  # DB: 
  #   image: mariadb
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
