
version: "3.8"

networks:
  inception:
    name: inception
services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb:najat
    env_file:
      - .env
    networks:
      -  inception
    restart: on-failure
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:najat
    ports:
      - 443:443
    restart: on-failure
    # volumes:
    #   - ./mariadb_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"  # Expose port for debugging
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress:najat
    restart: on-failure
    networks:
      -  inception
    env_file:
      - .env


      # volumes:
    #   - WordPress:/var/www/html

  # volumes:
  # WordPress:
  #   driver: local
  #   driver_opts:
  #      o: bind
  #      type: none
  #      device: /home/nkhoudro/Desktop/data/WP
    # depends_on:
    #   - ma
  # wordpress:
  #    build: requirements/wordpress/
  #    container_name: wordpress
  #   image: wordpress:najat
  #   restart: always
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_NAME: wordpress
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: example
#     volumes:
#       - wordpress_data:/var/www/html
#     depends_on:
#       - mariadb
  
# volumes:
#   wordpress_data:
#   data:

    # ports:
    #   - 3306:3306
  # DB: 
  #   image: mariadb
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
