version : '3.7'
services:
  # nginx:
  #   build: requirements/nginx/
  #   container_name: nginx
  #   ports:
  #     - 443:443
  #   restart: always
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file:
      - .env
    # volumes:
    #   - ./data:/var/lib/mysql
    # ports:
    #   - 3306:3306
  # DB: 
  #   image: mariadb
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
