
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:najat
    ports:
      - 443:443
    restart: always
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb:najat
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress:najat
    restart: always
    env_file:
      - .env
    volumes:
      -wordpress:/var/www/html
    # ports:
    #   - 3306:3306
  # DB: 
  #   image: mariadb
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
