version : '3.7'
services:
  # nginx:
  #   build: requirements/nginx/
  #   container_name: nginx
  #   ports:
  #     - 443:443
  #   restart: always
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: passwordROOT
      MYSQL_DATABASE: mydata
      MYSQL_USER: najat
      MYSQL_PASSWORD: password
    # volumes:
    #   - ./data:/var/lib/mysql
    # ports:
    #   - 3306:3306
  # DB: 
  #   image: mariadb
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
